version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values.
    directory: "/" # Location of package manifests.
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
