#################################################
# Project metadata
#################################################

[project]
requires-python = ">=3.8"
name = "fastapi-nano"
version = "0.1.0"
description = "A minimal FastAPI project template."
readme = "README.md"
keywords = ["fastapi", "template", "minimal", "docker", "cookiecutter"]
license = {file = "LICENSE"}
authors = [{name = "Redowan Delowar", email = "redowan.nafi@gmail.com"}]
dependencies = [
    "bcrypt",
    "fastapi",
    "passlib",
    "python-multipart",
    "uvicorn",
    "gunicorn",
    "python-jose[cryptography]"
]

[project.optional-dependencies]
dev = [
    "black",
    "httpx",
    "mypy",
    "pip-tools",
    "pytest",
    "pytest-cov",
    "requests", # Required by fastapi-test.
    "ruff"
]
[project.urls]
Repository = "https://github.com/rednafi/fastapi-nano.git"

#################################################
# Mypy config
#################################################

[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
warn_no_return = true
warn_unused_ignores = true
allow_untyped_globals = true
allow_redefinition = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
pretty = true

[[tool.mypy.overrides]]
module = "app.tests.*"
ignore_errors = true

#################################################
# Ruff config
#################################################

[tool.ruff]
line-length = 88

# Enable Pyflakes `E` and `F` codes by default
select = ["E", "F", "I001", "PT", "C4"]
ignore = ["E501"]
respect-gitignore = true

per-file-ignores = {}

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10
max-complexity = 10

#################################################
# Pytest config
#################################################

[tool.pytest.ini_options]
addopts = "--strict-markers --maxfail 1 --cov src tests/ --no-header"
markers = """
    integration: mark a test as an integration test.
"""
console_output_style = "progress"

#################################################
# Setuptools config
#################################################

[tool.setuptools.packages.find]
where = ["app"]  # ["."] by default
